version: "3"

services:

  wikijs:
    build:
      context: .
      dockerfile: Dockerfile
    image: wikijs_git:2
    container_name: wikijs
    restart: unless-stopped
    networks:
      - cpnet-docker-network
    volumes:
      - ./keys/id_rsa:/home/node/.ssh/id_rsa:ro
      - ./keys/id_rsa.pub:/home/node/.ssh/id_rsa.pub:ro
    environment:
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${WIKIJS_DB_NAME}
    ports:
      - "8082:3000"
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthz"]
      interval: 5m
      timeout: 30s
      retries: 3

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${UMAMI_DB_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_SECRET}
    ports:
    - "8083:3000"
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "curl -f http://localhost:3000/"]
      interval: 5m
      timeout: 30s
      retries: 3

  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    networks:
      - cpnet-docker-network
    volumes:
      - "linkding-data:/etc/linkding/data"
    environment:
      LD_HOST_DATA_DIR: ./data
      LD_SUPERUSER_NAME: ${LINKDING_USER}
      LD_SUPERUSER_PASSWORD: ${LINKDING_PASS}
      LD_DISABLE_BACKGROUND_TASKS: False
      LD_DISABLE_URL_VALIDATION: False
      LD_ENABLE_AUTH_PROXY: False
      LD_DB_ENGINE: sqlite
    ports:
      - "8084:9090"
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "curl -f http://localhost:9090/"]
      interval: 5m
      timeout: 30s
      retries: 3

networks:
    cpnet-docker-network:
      driver: bridge

volumes:
  linkding-data:
    driver: local
