version: "3"

services:

  postgres_server:
    image: postgres:16-alpine
    container_name: postgres_server
    restart: unless-stopped
    networks:
      - cpnet-docker-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      WIKIJS_DB_NAME: ${WIKIJS_DB_NAME}
      UMAMI_DB_NAME: ${UMAMI_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "psql -U docker_db -d docker_db -c 'SELECT 1' > /dev/null || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 3

  wikijs:
    build:
      context: .
      dockerfile: Dockerfile
    image: wikijs_git:2
    container_name: wikijs
    restart: unless-stopped
    depends_on:
      - postgres_server
    networks:
      - cpnet-docker-network
    volumes:
      - ./keys/id_rsa:/home/node/.ssh/id_rsa:ro
      - ./keys/id_rsa.pub:/home/node/.ssh/id_rsa.pub:ro
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres_server
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${WIKIJS_DB_NAME}
    ports:
      - "8082:3000"
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "curl -f http://localhost:3000/healthz"]
      interval: 5m
      timeout: 30s
      retries: 3

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: unless-stopped
    depends_on:
    - postgres_server
    networks:
    - cpnet-docker-network
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@postgres_server:5432/${UMAMI_DB_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_SECRET}
    ports:
      - "8083:3000"
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "curl -f http://localhost:3000/"]
      interval: 5m
      timeout: 30s
      retries: 3

  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    restart: unless-stopped
    networks:
      - cpnet-docker-network
    volumes:
      - "linkding-data:/etc/linkding/data"
    environment:
      LD_HOST_DATA_DIR: ./data
      LD_SUPERUSER_NAME: ${LINKDING_USER}
      LD_SUPERUSER_PASSWORD: ${LINKDING_PASS}
      LD_DISABLE_BACKGROUND_TASKS: False
      LD_DISABLE_URL_VALIDATION: False
      LD_ENABLE_AUTH_PROXY: False
      LD_DB_ENGINE: sqlite
    ports:
      - "8084:9090"
    healthcheck:
      start_period: 1m
      test: ["CMD-SHELL", "curl -f http://localhost:9090/"]
      interval: 5m
      timeout: 30s
      retries: 3

networks:
    cpnet-docker-network:
      driver: bridge

volumes:
  postgres-data:
    driver: local
  linkding-data:
    driver: local
